server:
  port: 9191
  
eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/users/**
        
      - id: CLAIM-SERVICE
        uri: lb://CLAIM-SERVICE
        predicates:
        - Path=/claims/**
      
       
 